stages:
  - Compile
  - Test

build:
  stage: Compile
  tags:
    - Shell
  script:
    - mvn clean compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - Shell
  script:
    - mvn clean verify
    - python3.6 coverage.py
  allow_failure: false
