stages:
  - Clean
  - Compile
  - Test

clean:
  stage: Build
  tags:
    - Shell
  script:
    - mvn clean
  allow_failure: false

build:
  stage: Compile
  tags:
    - Shell
  script:
    - mvn compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - Shell
  script:
    - mvn test
  allow_failure: true
