# The Yaml

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  
ignore:
  - "src/main/java/nz/ac/vuw/engr301/group9mcs/view/*"
  - "src/main/java/nz/ac/vuw/engr301/group9mcs/controller/*"
  - "src/main/java/nz/ac/vuw/engr301/group9mcs/view/**/*"
  - "src/main/java/nz/ac/vuw/engr301/group9mcs/controller/**/*"
