# This is a basic workflow to help you get started with Actions
name: build

on: push
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
      - name: Maven Compile
        run: mvn clean compile
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: mvn clean verify
      - run: python3.6 coverage.py
