# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: /*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: shell
    steps:
      - run: mvn clean compile
  test:
    needs: [build]
    runs-on: shell
    steps:
      - run: mvn clean verify
      - run: python3.6 coverage.py
